name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deployPsGallery:
    name: "Deploy to PSGallery"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Deploy to PSGallery
          shell: pwsh
          run: |
            $publishedVersion = Find-Module -Name NHLPS | Select -ExpandProperty "Version"
            $gitVersion = Import-PowerShellDataFile -Path "./NHLPS/NHLPS.psd1" | Select -ExpandProperty "ModuleVersion"
            if ($gitVersion -gt $publishedVersion) {
                Write-Host "Module manifest version $gitVersion IS greater than PSGallery version $publishedVersion" -ForeGroundColor "Green"
                Write-Host "Deploying NHLPS to PSGallery - https://www.powershellgallery.com/packages/NHLPS/$gitVersion" -ForeGroundColor "Green"

                Publish-Module -Path "./NHLPS/" -NugetAPIKey "${{ secrets.NUGETAPIKEY }}" 
            } else {
                Write-Warning "Module manifest version $gitVersion NOT greater than PSGallery version $publishedVersion"
                Write-Warning "Skipping deployment to PSGallery"
            }