# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test module
        id: test_module
        uses: zyborg/pester-tests-report@v1
        with:
          # include_paths: Tests
          report_name: NHLPS Pester Tests
          report_title: NHLPS Pester Tests
          # github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: dump test results
        shell: pwsh
        run: |
          Write-Host 'Total Tests Executed...:  ${{ steps.test_module.outputs.total_count }}'
          Write-Host 'Total Tests PASSED.....:  ${{ steps.test_module.outputs.passed_count }}'
          Write-Host 'Total Tests FAILED.....:  ${{ steps.test_module.outputs.failed_count }}'
